name: GitHub Actions Demo
run-name: run CI/CD 🚀
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    init:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [17.x]
        steps:
            - uses: actions/checkout@v3
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules
              run: npm install
            - name: build project
              run: npm run build
            - name: build storybook
              run: npm run build:storybook
            - name: unit test
              run: npm run test:unit
            - name: e2e test
              run: npm run test:e2e
            - name: lint code
              run: npm run lint
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        strategy:
            matrix:
                node-version: [17.x]
        env:
            github_token: ${{ process.env.REACT_APP_EHB_ACCESS_KEY }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: install Dependencies
              run: npm install
            - name: build Project
              run: npm run build
            - name: deploy
              run: |
                  git config --global user.name ${{ github.actor }}
                  git config --global user.email 'n.kerd@mail.ru'
                  git remote set-url origin https://${github_token}@github.com/${repository}
                  npm run deploy
              env:
                  user_name: 'github-actions[bot]'
                  user_email: 'github-actions[bot]@users.noreply.github.com'
                  github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
                  repository: ${{ github.repository }}
