name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    init:
        runs-on: windows-latest
        strategy:
            matrix:
                node-version: [17.x]
        steps:
            - uses: actions/checkout@v3
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules
              run: npm install
            - name: build project
              run: npm run build
            - name: build storybook
              run: npm run build:storybook
            - name: unit test
              run: npm run test:unit
            - name: e2e test
              run: npm run test:e2e
            - name: lint code
              run: npm run lint
    deploy:
        runs-on: windows-latest
        steps:
            - name: Checkout main branch
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: '14.x'

            - name: Install dependencies
              run: npm install

            - name: Build and deploy to Github Pages
              run: |
                  npm run build
                  git config --global user.name 'Natela'
                  git config --global user.email 'nat.kerdzevadze@gmail.com'
                  git checkout gh-pages
                  git add .
                  git commit -m "Update gh-pages"
                  git push -u origin gh-pages
